// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT !

    uint32_t gamesound[] = {
        0x00000000,0x000075EC,     // 0000 - sound_ping.wav
        0x000075EC,0x0000227C,     // 0001 - sound_mine.wav
        0x00009868,0x0000258C,     // 0002 - sound_beetle.wav
        0x0000BDF4,0x00001300,     // 0003 - sound_wheel.wav
        0x0000D0F4,0x000061CC,     // 0004 - sound_alien.wav
        0x000132C0,0x00002194,     // 0005 - sound_magic_wall.wav
        0x00015454,0x0000130C,     // 0006 - sound_man_space.wav
        0x00016760,0x0000DA6C,     // 0007 - sound_door.wav
        0x000241CC,0x000073AC,     // 0008 - sound_nut.wav
        0x0002B578,0x0000179C,     // 0009 - sound_nut_crack.wav
        0x0002CD14,0x0000C8AC,     // 0010 - sound_replicator.wav
        0x000395C0,0x00006EFC,     // 0011 - sound_man_push.wav
        0x000404BC,0x00002D8C,     // 0012 - sound_yam.wav
        0x00043248,0x00004A9C,     // 0013 - sound_stone.wav
        0x00047CE4,0x0000EA4C,     // 0014 - sound_explosion.wav
        0x00056730,0x00000D94,     // 0015 - sound_dynamite_tick.wav
        0x000574C4,0x00003A04,     // 0016 - sound_pool_blub.wav
        0x0005AEC8,0x000058EC,     // 0017 - sound_man_take.wav
        0x000607B4,0x0000289C,     // 0018 - sound_man_dig.wav
        0x00063050,0x0000CECC,     // 0019 - sound_door_exit.wav
        0x0006FF1C,0x000057BC,     // 0020 - sound_man_cry.wav
        0x000756D8,0x00003C6C,     // 0021 - sound_cheese.wav
        0x00079344,0x0000FEAC,     // 0022 - sound_gong.wav
        0x000891F0,0x0000801C,     // 0023 - sound_squeeze.wav
        0x0009120C,0x00001754,     // 0024 - sound_switch.wav
        0x00092960,0x0000229C,     // 0025 - sound_mole.wav
        0x00094BFC,0x000019C4,     // 0026 - sound_wheel_door_time.wav
        0x000965C0,0x000085F2,     // 0027 - sound_door_close_open.wav
        0x0009EBB2,0x0000222C,     // 0028 - sound_replicator_plop.wav
        0x000A0DDE,0x00005EAC,     // 0029 - sound_dynamite_start.wav
        0x000A6C8A,0x000072A4,     // 0030 - sound_conveyorbelt.wav
        0x000ADF2E,0x0000AD4C,     // 0031 - sound_teleporter.wav
        0x000B8C7A,0x0000C22C,     // 0032 - sound_steel_wall_grow.wav
        0x000C4EA6,0x00005D64,     // 0033 - sound_bomb_remote.wav
        0x000CAC0A,0x00004A7C,     // 0034 - sound_pipe.wav
        0x000CF686,0x0000E32C,     // 0035 - sound_shield_end.wav
        0x000DD9B2,0x00004CFC,     // 0036 - sound_slime_slurp.wav
        0x000E26AE,0x0000B02C,     // 0037 - sound_slime_move.wav
        0xFFFFFFFF,0xFFFFFFFF      // Endekennung
        };
