// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT !

    uint32_t music[] = {
        0x00000000,0x0000A4F8,     // 0000 - echoing2.mod
        0x0000A4F8,0x0000527C,     // 0001 - circus_time_2_1993.mod
        0x0000F774,0x000035C6,     // 0002 - class01.mod
        0x00012D3A,0x00031FB8,     // 0003 - gtrash3f.mod
        0x00044CF2,0x00002B3A,     // 0004 - class11.mod
        0x0004782C,0x00003658,     // 0005 - 2kad04.mod
        0x0004AE84,0x00002680,     // 0006 - 2kad02.mod
        0x0004D504,0x000028F2,     // 0007 - brewery.mod
        0x0004FDF6,0x00003BDA,     // 0008 - class05_1999.mod
        0x000539D0,0x00003500,     // 0009 - softworld.mod
        0xFFFFFFFF,0xFFFFFFFF      // Endekennung
        };
